In [3]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('C:\\Users\\DELL\\anaconda3\\Lib\\site-packages\\datashader\\examples\\data\\.data_stubs\\nyc_taxi.csv')

In [5]:
df.head()

Unnamed: 0  VendorID tpep_pickup_datetime tpep_dropoff_datetime  \
0    10064589         2  2015-01-01 20:20:57   2015-01-01 20:30:39   
1     8451911         1  2015-01-15 12:35:56   2015-01-15 12:52:29   
2     1030538         1  2015-01-02 22:02:55   2015-01-02 22:09:17   
3     8061903         2  2015-01-19 09:47:07   2015-01-19 09:50:40   
4     6446658         2  2015-01-09 17:32:26   2015-01-09 17:52:10   

   passenger_count  trip_distance      pickup_x      pickup_y  RateCodeID  \
0                1           4.02 -8.232723e+06  4.979400e+06           1   
1                1           2.40 -8.233768e+06  4.979199e+06           1   
2                1           0.90 -8.236912e+06  4.972484e+06           1   
3                2           1.01 -8.232874e+06  4.979104e+06           1   
4                5           2.73 -8.236896e+06  4.976339e+06           1   

  store_and_fwd_flag     dropoff_x     dropoff_y  payment_type  fare_amount  \
0                  N -8.235438e+06  4.973928e+06             1         13.5   
1                  N -8.236276e+06  4.974675e+06             1         12.0   
2                  N -8.235815e+06  4.972018e+06             1          5.7   
3                  N -8.231489e+06  4.979778e+06             2          5.0   
4                  N -8.235296e+06  4.972574e+06             1         14.0   

   extra  mta_tax  tip_amount  tolls_amount  improvement_surcharge  \
0    0.5      0.5        1.50           0.0                    0.3   
1    0.0      0.5        2.55           0.0                    0.3   
2    0.5      0.5        1.40           0.0                    0.0   
3    0.0      0.5        0.00           0.0                    0.3   
4    1.0      0.5        3.00           0.0                    0.3   

   total_amount  
0         16.30  
1         15.35  
2          8.40  
3          5.80  
4         18.80

In [6]:
df['fare_amount'].describe()

count    50000.000000
mean         9.432078
std          5.292303
min         -4.500000
25%          6.000000
50%          8.000000
75%         11.500000
max        400.000000
Name: fare_amount, dtype: float64

In [7]:
def haversine_distance(df, lat1, long1, lat2, long2):
    r = 6371  # Earth's radius in kilometers
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    
    delta_phi = np.radians(df[lat2] - df[lat1])
    delta_lambda = np.radians(df[long2] - df[long1])
    
    a = np.sin(delta_phi / 2) ** 2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    d = r * c
    
    return d


In [8]:
df.columns

Index(['Unnamed: 0', 'VendorID', 'tpep_pickup_datetime',
       'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'pickup_x',
       'pickup_y', 'RateCodeID', 'store_and_fwd_flag', 'dropoff_x',
       'dropoff_y', 'payment_type', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount'],
      dtype='object')

In [9]:
df['dist_km']=haversine_distance(df,'pickup_x','pickup_y', 'dropoff_x','dropoff_y' )

In [10]:
df.head()

Unnamed: 0  VendorID tpep_pickup_datetime tpep_dropoff_datetime  \
0    10064589         2  2015-01-01 20:20:57   2015-01-01 20:30:39   
1     8451911         1  2015-01-15 12:35:56   2015-01-15 12:52:29   
2     1030538         1  2015-01-02 22:02:55   2015-01-02 22:09:17   
3     8061903         2  2015-01-19 09:47:07   2015-01-19 09:50:40   
4     6446658         2  2015-01-09 17:32:26   2015-01-09 17:52:10   

   passenger_count  trip_distance      pickup_x      pickup_y  RateCodeID  \
0                1           4.02 -8.232723e+06  4.979400e+06           1   
1                1           2.40 -8.233768e+06  4.979199e+06           1   
2                1           0.90 -8.236912e+06  4.972484e+06           1   
3                2           1.01 -8.232874e+06  4.979104e+06           1   
4                5           2.73 -8.236896e+06  4.976339e+06           1   

  store_and_fwd_flag  ...     dropoff_y  payment_type  fare_amount  extra  \
0                  N  ...  4.973928e+06             1         13.5    0.5   
1                  N  ...  4.974675e+06             1         12.0    0.0   
2                  N  ...  4.972018e+06             1          5.7    0.5   
3                  N  ...  4.979778e+06             2          5.0    0.0   
4                  N  ...  4.972574e+06             1         14.0    1.0   

   mta_tax  tip_amount  tolls_amount  improvement_surcharge  total_amount  \
0      0.5        1.50           0.0                    0.3         16.30   
1      0.5        2.55           0.0                    0.3         15.35   
2      0.5        1.40           0.0                    0.0          8.40   
3      0.5        0.00           0.0                    0.3          5.80   
4      0.5        3.00           0.0                    0.3         18.80   

        dist_km  
0  17146.288437  
1  14535.339756  
2   2621.057632  
3   6122.656650  
4  16532.803377  

[5 rows x 21 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0             50000 non-null  int64  
 1   VendorID               50000 non-null  int64  
 2   tpep_pickup_datetime   50000 non-null  object 
 3   tpep_dropoff_datetime  50000 non-null  object 
 4   passenger_count        50000 non-null  int64  
 5   trip_distance          50000 non-null  float64
 6   pickup_x               50000 non-null  float64
 7   pickup_y               50000 non-null  float64
 8   RateCodeID             50000 non-null  int64  
 9   store_and_fwd_flag     50000 non-null  object 
 10  dropoff_x              50000 non-null  float64
 11  dropoff_y              50000 non-null  float64
 12  payment_type           50000 non-null  int64  
 13  fare_amount            50000 non-null  float64
 14  extra                  50000 non-null  float64
 15  mt

In [12]:
df['tpep_pickup_datetime']=pd.to_datetime(df['tpep_pickup_datetime'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Unnamed: 0             50000 non-null  int64         
 1   VendorID               50000 non-null  int64         
 2   tpep_pickup_datetime   50000 non-null  datetime64[ns]
 3   tpep_dropoff_datetime  50000 non-null  object        
 4   passenger_count        50000 non-null  int64         
 5   trip_distance          50000 non-null  float64       
 6   pickup_x               50000 non-null  float64       
 7   pickup_y               50000 non-null  float64       
 8   RateCodeID             50000 non-null  int64         
 9   store_and_fwd_flag     50000 non-null  object        
 10  dropoff_x              50000 non-null  float64       
 11  dropoff_y              50000 non-null  float64       
 12  payment_type           50000 non-null  int64         
 13  f

In [14]:
# Assuming your DataFrame is named df
df['pickup_datetime'] = df['tpep_pickup_datetime']  # Renaming pickup datetime
df['pickup_longitude'] = df['pickup_x']             # Renaming pickup longitude
df['pickup_latitude'] = df['pickup_y']              # Renaming pickup latitude
df['dropoff_latitude'] = df['dropoff_y']            # Renaming dropoff latitude
df['dropoff_longitude'] = df['dropoff_x']           # Renaming dropoff longitude

# Creating fare_class based on fare_amount
def classify_fare(fare):
    if fare < 10:
        return 'Low'
    elif 10 <= fare < 30:
        return 'Medium'
    else:
        return 'High'

df['fare_class'] = df['fare_amount'].apply(classify_fare)

# Selecting only the needed columns
df_needed = df[['pickup_datetime', 'fare_amount', 'fare_class', 
                'pickup_longitude', 'pickup_latitude', 'dropoff_latitude', 
                'dropoff_longitude', 'passenger_count', 'dist_km']]

# Displaying the new dataset
print(df_needed.head())


      pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5     Medium     -8.232723e+06   
1 2015-01-15 12:35:56         12.0     Medium     -8.233768e+06   
2 2015-01-02 22:02:55          5.7        Low     -8.236912e+06   
3 2015-01-19 09:47:07          5.0        Low     -8.232874e+06   
4 2015-01-09 17:32:26         14.0     Medium     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km  
0  17146.288437  
1  14535.339756  
2   2621.057632  
3   6122.656650  
4  16532.803377  


In [15]:

def classify_fare(fare):
    if fare < 10:
        return '0'
    elif 10 <= fare < 30:
        return '1'
    else:
        return '2'

df['fare_class'] = df['fare_amount'].apply(classify_fare)


# Apply the classify_fare function and avoid the SettingWithCopyWarning
df.loc[:, 'fare_class'] = df['fare_amount'].apply(classify_fare)

# Selecting only the needed columns
df = df[['pickup_datetime', 'fare_amount', 'fare_class', 
                'pickup_longitude', 'pickup_latitude', 'dropoff_latitude', 
                'dropoff_longitude', 'passenger_count', 'dist_km']]

# Displaying the new dataset
print(df_needed.head())



      pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5     Medium     -8.232723e+06   
1 2015-01-15 12:35:56         12.0     Medium     -8.233768e+06   
2 2015-01-02 22:02:55          5.7        Low     -8.236912e+06   
3 2015-01-19 09:47:07          5.0        Low     -8.232874e+06   
4 2015-01-09 17:32:26         14.0     Medium     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km  
0  17146.288437  
1  14535.339756  
2   2621.057632  
3   6122.656650  
4  16532.803377  


In [16]:
df.head()

pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5          1     -8.232723e+06   
1 2015-01-15 12:35:56         12.0          1     -8.233768e+06   
2 2015-01-02 22:02:55          5.7          0     -8.236912e+06   
3 2015-01-19 09:47:07          5.0          0     -8.232874e+06   
4 2015-01-09 17:32:26         14.0          1     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km  
0  17146.288437  
1  14535.339756  
2   2621.057632  
3   6122.656650  
4  16532.803377

In [17]:
my_time=df['pickup_datetime'][0]

In [18]:
my_time

Timestamp('2015-01-01 20:20:57')

In [19]:
my_time.hour

20

In [20]:
import pandas as pd

# Example timestamp
ts = pd.Timestamp('2015-01-01 20:20:57')

# Check timezone
print(ts.tzinfo)  # This will return None if no timezone is set


None


In [21]:
# Localizing the datetime column to New York time
df['pickup_datetime'] = df['pickup_datetime'].dt.tz_localize('America/New_York')


In [22]:
df.head()

pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57-05:00         13.5          1     -8.232723e+06   
1 2015-01-15 12:35:56-05:00         12.0          1     -8.233768e+06   
2 2015-01-02 22:02:55-05:00          5.7          0     -8.236912e+06   
3 2015-01-19 09:47:07-05:00          5.0          0     -8.232874e+06   
4 2015-01-09 17:32:26-05:00         14.0          1     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km  
0  17146.288437  
1  14535.339756  
2   2621.057632  
3   6122.656650  
4  16532.803377

In [23]:
df['pickup_datetime'] = df['pickup_datetime'].dt.tz_localize(None)

In [24]:
# Localizing the datetime column to New York time
df['EDTdate'] = df['pickup_datetime'].dt.tz_localize('America/New_York')


In [25]:
df.head()

pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5          1     -8.232723e+06   
1 2015-01-15 12:35:56         12.0          1     -8.233768e+06   
2 2015-01-02 22:02:55          5.7          0     -8.236912e+06   
3 2015-01-19 09:47:07          5.0          0     -8.232874e+06   
4 2015-01-09 17:32:26         14.0          1     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km                   EDTdate  
0  17146.288437 2015-01-01 20:20:57-05:00  
1  14535.339756 2015-01-15 12:35:56-05:00  
2   2621.057632 2015-01-02 22:02:55-05:00  
3   6122.656650 2015-01-19 09:47:07-05:00  
4  16532.803377 2015-01-09 17:32:26-05:00

In [26]:
df['Hour']=df['EDTdate'].dt.hour

In [27]:
df['Hour']

0        20
1        12
2        22
3         9
4        17
         ..
49995     7
49996    11
49997    20
49998     8
49999     9
Name: Hour, Length: 50000, dtype: int32

In [28]:
df['AMorPM']=np.where(df['Hour']<12, 'am', 'pm')

In [29]:
df.head()

pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5          1     -8.232723e+06   
1 2015-01-15 12:35:56         12.0          1     -8.233768e+06   
2 2015-01-02 22:02:55          5.7          0     -8.236912e+06   
3 2015-01-19 09:47:07          5.0          0     -8.232874e+06   
4 2015-01-09 17:32:26         14.0          1     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km                   EDTdate  Hour AMorPM  
0  17146.288437 2015-01-01 20:20:57-05:00    20     pm  
1  14535.339756 2015-01-15 12:35:56-05:00    12     pm  
2   2621.057632 2015-01-02 22:02:55-05:00    22     pm  
3   6122.656650 2015-01-19 09:47:07-05:00     9     am  
4  16532.803377 2015-01-09 17:32:26-05:00    17     pm

In [30]:
df['Weekday']=df['EDTdate'].dt.strftime("%a")

In [31]:
df.head()

pickup_datetime  fare_amount fare_class  pickup_longitude  \
0 2015-01-01 20:20:57         13.5          1     -8.232723e+06   
1 2015-01-15 12:35:56         12.0          1     -8.233768e+06   
2 2015-01-02 22:02:55          5.7          0     -8.236912e+06   
3 2015-01-19 09:47:07          5.0          0     -8.232874e+06   
4 2015-01-09 17:32:26         14.0          1     -8.236896e+06   

   pickup_latitude  dropoff_latitude  dropoff_longitude  passenger_count  \
0     4.979400e+06      4.973928e+06      -8.235438e+06                1   
1     4.979199e+06      4.974675e+06      -8.236276e+06                1   
2     4.972484e+06      4.972018e+06      -8.235815e+06                1   
3     4.979104e+06      4.979778e+06      -8.231489e+06                2   
4     4.976339e+06      4.972574e+06      -8.235296e+06                5   

        dist_km                   EDTdate  Hour AMorPM Weekday  
0  17146.288437 2015-01-01 20:20:57-05:00    20     pm     Thu  
1  14535.339756 2015-01-15 12:35:56-05:00    12     pm     Thu  
2   2621.057632 2015-01-02 22:02:55-05:00    22     pm     Fri  
3   6122.656650 2015-01-19 09:47:07-05:00     9     am     Mon  
4  16532.803377 2015-01-09 17:32:26-05:00    17     pm     Fri

In [32]:
cat_cols=['Hour', 'AMorPM', 'Weekday']
cont_cols=['pickup_longitude',
       'pickup_latitude', 'dropoff_latitude', 'dropoff_longitude',
       'passenger_count', 'dist_km', 'EDTdate']

In [33]:
y_col=['fare_amount']

In [34]:
df.dtypes

pickup_datetime                        datetime64[ns]
fare_amount                                   float64
fare_class                                     object
pickup_longitude                              float64
pickup_latitude                               float64
dropoff_latitude                              float64
dropoff_longitude                             float64
passenger_count                                 int64
dist_km                                       float64
EDTdate              datetime64[ns, America/New_York]
Hour                                            int32
AMorPM                                         object
Weekday                                        object
dtype: object

In [35]:
for cat in cat_cols:
    df[cat]=df[cat].astype('category')

In [36]:
df.dtypes

pickup_datetime                        datetime64[ns]
fare_amount                                   float64
fare_class                                     object
pickup_longitude                              float64
pickup_latitude                               float64
dropoff_latitude                              float64
dropoff_longitude                             float64
passenger_count                                 int64
dist_km                                       float64
EDTdate              datetime64[ns, America/New_York]
Hour                                         category
AMorPM                                       category
Weekday                                      category
dtype: object

In [37]:
df['Hour'].head()

0    20
1    12
2    22
3     9
4    17
Name: Hour, dtype: category
Categories (24, int32): [0, 1, 2, 3, ..., 20, 21, 22, 23]

In [38]:
df['AMorPM'].head()

0    pm
1    pm
2    pm
3    am
4    pm
Name: AMorPM, dtype: category
Categories (2, object): ['am', 'pm']

In [39]:
df['Weekday'].head()

0    Thu
1    Thu
2    Fri
3    Mon
4    Fri
Name: Weekday, dtype: category
Categories (7, object): ['Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed']

In [40]:
df['AMorPM'].cat.codes

0        1
1        1
2        1
3        0
4        1
        ..
49995    0
49996    0
49997    1
49998    0
49999    0
Length: 50000, dtype: int8

In [41]:
df['Weekday'].cat.codes

0        4
1        4
2        0
3        1
4        0
        ..
49995    3
49996    3
49997    1
49998    6
49999    2
Length: 50000, dtype: int8

In [42]:
hr=df['Hour'].cat.codes.values

In [43]:
ampm=df['AMorPM'].cat.codes.values

In [44]:
wkdy=df['Weekday'].cat.codes.values

In [45]:
hr

array([20, 12, 22, ..., 20,  8,  9], dtype=int8)

In [46]:
cats=np.stack([hr,ampm,wkdy], axis=1)

In [47]:
cats

array([[20,  1,  4],
       [12,  1,  4],
       [22,  1,  0],
       ...,
       [20,  1,  1],
       [ 8,  0,  6],
       [ 9,  0,  2]], dtype=int8)

In [48]:
# cats=np.stack([df[col].cat.codes.values for col in cat_cols], 1)

In [51]:
cats=torch.tensor(cats, dtype=torch.int64)

C:\Users\DELL\AppData\Local\Temp\ipykernel_19108\2741758102.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cats=torch.tensor(cats, dtype=torch.int64)


In [54]:
conts = np.empty((len(df), len(cont_cols)), dtype=object)
for i, col in enumerate(cont_cols):
    conts[:, i] = df[col].values


In [55]:
conts

array([[-8232723.17128, 4979400.40941, 4973927.72595, ..., 1,
        17146.288437009887, 1420161657000000000],
       [-8233767.81067, 4979199.09578, 4974675.40007, ..., 1,
        14535.339756180507, 1421343356000000000],
       [-8236911.92043, 4972483.54292, 4972017.88562, ..., 1,
        2621.0576324090443, 1420254175000000000],
       ...,
       [-8234880.39408, 4976405.246280001, 4979213.67546, ..., 1,
        8286.06016119512, 1420509168000000000],
       [-8233377.981819999, 4976405.80688, 4976584.63866, ..., 2,
        2549.3841193080757, 1421241363000000000],
       [-8235019.679330001, 4974012.35486, 4974369.37361, ..., 1,
        341.10929298905467, 1421503669000000000]], dtype=object)

In [56]:
conts=torch.tensor(conts, dtype=torch.float)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

In [58]:
y=torch.tensor(df[y_col].values, dtype=torch.float).reshape(-1,1)

In [60]:
cats.shape


torch.Size([50000, 3])

In [61]:
conts.shape

(50000, 7)

In [62]:
y.shape

torch.Size([50000, 1])

In [63]:
cat_szs=[len(df[col].cat.categories) for col in cat_cols]

In [64]:
cat_szs

[24, 2, 7]

In [65]:
emb_szs=[(size, min(50,(size+1)//2))for size in cat_szs]

In [66]:
emb_szs

[(24, 12), (2, 1), (7, 4)]

In [67]:
cats

tensor([[20,  1,  4],
        [12,  1,  4],
        [22,  1,  0],
        ...,
        [20,  1,  1],
        [ 8,  0,  6],
        [ 9,  0,  2]])

In [68]:
catz=cats[:4]

In [69]:
catz

tensor([[20,  1,  4],
        [12,  1,  4],
        [22,  1,  0],
        [ 9,  0,  1]])

In [72]:
selfembeds=nn.ModuleList([nn.Embedding(ni,nf) for ni,nf in emb_szs])

In [73]:
selfembeds

ModuleList(
  (0): Embedding(24, 12)
  (1): Embedding(2, 1)
  (2): Embedding(7, 4)
)

In [74]:
embeddingz=[]
for i,e in enumerate(selfembeds):
    embeddingz.append(e(catz[:,i]))

In [75]:
embeddingz

[tensor([[ 0.8044, -0.1459, -0.2535,  0.7529,  1.1768, -0.0917,  1.0710,  0.9847,
          -0.4119,  1.5192,  2.2041,  0.7134],
         [ 0.4395,  1.1277,  0.3029,  0.0318, -0.1959,  1.0521,  2.2684, -0.5855,
          -0.5181, -1.1269, -1.1959, -1.3175],
         [-0.1415,  0.2468,  0.7479, -0.8141, -1.0952,  2.1818, -0.2108,  1.0112,
           0.4466,  1.1434,  0.1102, -0.1492],
         [-1.3130, -0.0895, -0.5708,  1.4675,  1.7857,  1.0065,  0.2829, -0.0259,
          -0.6325,  0.2383, -1.4672,  0.6945]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.3910],
         [-0.3910],
         [-0.3910],
         [ 1.0711]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.3780, -2.1146, -0.6134, -1.8214],
         [ 0.3780, -2.1146, -0.6134, -1.8214],
         [-0.6709,  0.4657,  0.2419,  2.9577],
         [-0.5093, -0.7493, -0.0062,  0.6616]], grad_fn=<EmbeddingBackward0>)]

In [76]:
z=torch.cat(embeddingz,1)

In [77]:
z

tensor([[ 0.8044, -0.1459, -0.2535,  0.7529,  1.1768, -0.0917,  1.0710,  0.9847,
         -0.4119,  1.5192,  2.2041,  0.7134, -0.3910,  0.3780, -2.1146, -0.6134,
         -1.8214],
        [ 0.4395,  1.1277,  0.3029,  0.0318, -0.1959,  1.0521,  2.2684, -0.5855,
         -0.5181, -1.1269, -1.1959, -1.3175, -0.3910,  0.3780, -2.1146, -0.6134,
         -1.8214],
        [-0.1415,  0.2468,  0.7479, -0.8141, -1.0952,  2.1818, -0.2108,  1.0112,
          0.4466,  1.1434,  0.1102, -0.1492, -0.3910, -0.6709,  0.4657,  0.2419,
          2.9577],
        [-1.3130, -0.0895, -0.5708,  1.4675,  1.7857,  1.0065,  0.2829, -0.0259,
         -0.6325,  0.2383, -1.4672,  0.6945,  1.0711, -0.5093, -0.7493, -0.0062,
          0.6616]], grad_fn=<CatBackward0>)

In [78]:
selfembedrop=nn.Dropout(0.4)

In [79]:
z=selfembedrop(z)

In [80]:
z

tensor([[ 1.3407, -0.2431, -0.4225,  1.2548,  0.0000, -0.0000,  1.7850,  1.6412,
         -0.0000,  2.5320,  0.0000,  1.1891, -0.6517,  0.6300, -0.0000, -1.0224,
         -3.0357],
        [ 0.7326,  1.8795,  0.0000,  0.0531, -0.3266,  1.7535,  3.7806, -0.0000,
         -0.0000, -0.0000, -1.9932, -2.1958, -0.6517,  0.6300, -0.0000, -1.0224,
         -0.0000],
        [-0.2358,  0.0000,  1.2464, -0.0000, -1.8253,  0.0000, -0.3514,  0.0000,
          0.7444,  1.9056,  0.0000, -0.0000, -0.6517, -0.0000,  0.7761,  0.0000,
          4.9295],
        [-2.1884, -0.1492, -0.9514,  2.4458,  0.0000,  1.6774,  0.4714, -0.0432,
         -0.0000,  0.3971, -0.0000,  0.0000,  1.7851, -0.8489, -1.2488, -0.0000,
          0.0000]], grad_fn=<MulBackward0>)

In [ ]:
class TabularModel(nn.Module):
    def __init__(self, emb_szs, n_cont, out_sz, ):
        pass
    def __forward__(self):
        pass
    