In [1]:
import numpy as np

In [2]:
mylist=[1,2,3,4]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3, 4])

In [5]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix=np.array(mylist)

In [8]:
matrix.shape

(3, 3)

In [10]:
np.arange(0,4,2)

array([0, 2])

In [12]:
np.ones((3,3))+4 #can't do this on a normal python list

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [15]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.randint(1,100,4) #start limit, end limit, number of numbers 
#is evenly distrubuted, meaning, every number has equal probability to be chosen

array([82, 90, 15, 10])

In [21]:
np.random.seed(101) #removes the even distribution part, meaning, the same numbers are generated as long as the two lines are in the same cell
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [32]:
arr=np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
randomarr=np.random.randint(1,10,10)

In [36]:
randomarr

array([5, 9, 6, 1, 6, 9, 2, 4, 9, 4])

In [37]:
randomarr.max()

9

In [38]:
randomarr.min()#returns value

1

In [39]:
randomarr.argmax()

1

In [40]:
randomarr.argmin() #returns index 

3

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr[5]

5

In [43]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr=np.arange(11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
sli=arr[:5] #a pointer, not a copy

In [50]:
sli

array([0, 1, 2, 3, 4])

In [57]:
 sli[:]=99 #changes made here will be reflected in arr

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
arr_2d.shape

(3, 3)

In [66]:
arr_2d[2]

array([7, 8, 9])

In [67]:
arr_2d[:2,1:] #slicing of the array

array([[2, 3],
       [5, 6]])

In [68]:
arr=np.arange(11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
boolean= arr>4

In [72]:
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [73]:
arr[boolean]

array([ 5,  6,  7,  8,  9, 10])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [81]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [82]:
arr_2d.sum(axis=0) #coloumn wise sums

array([22, 26, 30])

In [83]:
arr_2d.sum(axis=1)#row wise sum

array([ 6, 15, 24, 33])

In [84]:
arr=np.zeros(10)

In [85]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
arr=np.ones(10)

In [87]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
arr=arr*5

In [89]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [90]:
arr=np.arange(10,51)

In [91]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [92]:
arr=np.arange(10,51,2)

In [93]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [94]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [95]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr=np.eye(3)

In [97]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.random.rand()

0.2323536618147607

In [99]:
np.random.rand(25)

array([0.08356143, 0.60354842, 0.72899276, 0.27623883, 0.68530633,
       0.51786747, 0.04848454, 0.13786924, 0.18696743, 0.9943179 ,
       0.5206654 , 0.57878954, 0.73481906, 0.54196177, 0.91315356,
       0.80792015, 0.40299783, 0.35722434, 0.95287671, 0.34363158,
       0.86509982, 0.83027771, 0.53816145, 0.92246937, 0.09714648])

In [100]:
arr=np.arange(1,101)

In [101]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [102]:
arr=arr/100

In [103]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [104]:
arr=np.linspace(0,1,20)

In [105]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [106]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [109]:
mat[3,4]

20

In [114]:
mat[:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [120]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [123]:
mat[mat>=16].reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat.sum()

325

In [125]:
mat.std()

7.211102550927978

In [126]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [127]:
import pandas as pd

In [129]:
arr=[10,20,30]

In [133]:
mylist=np.array(arr)
mylist

array([10, 20, 30])

In [134]:
labels=['a','b','c']

In [135]:
pd.Series(data=mylist, index=labels)

a    10
b    20
c    30
dtype: int32

In [136]:
ser1=pd.Series([1,2,3,4], index=['USA', 'Japan', 'Germany', 'Italy'])
ser1

USA        1
Japan      2
Germany    3
Italy      4
dtype: int64

In [137]:
ser2=pd.Series([1,2,3,4], index=['USA', 'Germany', 'Japan', 'Belgium'])
ser2

USA        1
Germany    2
Japan      3
Belgium    4
dtype: int64

In [138]:
ser1+ser2

Belgium    NaN
Germany    5.0
Italy      NaN
Japan      5.0
USA        2.0
dtype: float64

In [139]:
from numpy.random import randn 
np.random.seed(101)
rand_mat=randn(5,4)

In [140]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [144]:
df=pd.DataFrame(data=rand_mat, index='A B C D E'.split(), columns='W X Y Z'.split())

In [145]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [147]:
mylist=['W', 'Y']
df[mylist]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [150]:
df['NEW']=df['W']+df['Y']
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [155]:
df.drop('NEW', axis=1, inplace=True) #axis=1 means coloumn, nothing mentioned means row

In [156]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [160]:
df.iloc[[0,3]] #iloc for index based

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [161]:
df.loc['A'] #loc for name based

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [162]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [163]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [170]:
df[df['Y']>0]['Z'].loc['A']

0.5038257538223936

In [171]:
cond1=df['Y']>0
cond2=df['Z']>0

In [172]:
df[cond1 & cond2]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [173]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [174]:
new_col='Hyd Che Mum Del Kol'.split()
df['City']=new_col

In [175]:
df

W         X         Y         Z City
A  2.706850  0.628133  0.907969  0.503826  Hyd
B  0.651118 -0.319318 -0.848077  0.605965  Che
C -2.018168  0.740122  0.528813 -0.589001  Mum
D  0.188695 -0.758872 -0.933237  0.955057  Del
E  0.190794  1.978757  2.605967  0.683509  Kol

In [177]:
df.set_index('City')

W         X         Y         Z
City                                        
Hyd   2.706850  0.628133  0.907969  0.503826
Che   0.651118 -0.319318 -0.848077  0.605965
Mum  -2.018168  0.740122  0.528813 -0.589001
Del   0.188695 -0.758872 -0.933237  0.955057
Kol   0.190794  1.978757  2.605967  0.683509

In [178]:
count=df['W']>0
sum(count)

4

In [179]:
count.value_counts()

W
True     4
False    1
Name: count, dtype: int64

In [180]:
data={'Company':['GOOG', 'GOOG', 'MSTF', 'MSTF', 'FB', 'FB'], 'Person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'], 'Sales':[200,120,340,124,243,350]}

In [181]:
df=pd.DataFrame(data)

In [182]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSTF      Amy    340
3    MSTF  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [187]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSTF
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [188]:
df['Company'].unique()

array(['GOOG', 'MSTF', 'FB'], dtype=object)

In [189]:
def squared(number):
    return number*number

In [190]:
new_col=df['Sales'].apply(squared)
df['New']=new_col
df

Company   Person  Sales     New
0    GOOG      Sam    200   40000
1    GOOG  Charlie    120   14400
2    MSTF      Amy    340  115600
3    MSTF  Vanessa    124   15376
4      FB     Carl    243   59049
5      FB    Sarah    350  122500

In [192]:
del df['New']

In [193]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSTF      Amy    340
3    MSTF  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [196]:
df.sort_values('Person', ascending=False)

Company   Person  Sales
3    MSTF  Vanessa    124
5      FB    Sarah    350
0    GOOG      Sam    200
1    GOOG  Charlie    120
4      FB     Carl    243
2    MSTF      Amy    340

In [210]:
import os
print(os.listdir())


['.git', '000000000000_Processes Synchronization_05112023120457.pdf', '000000000000_PS2_11112023121510.pdf', '03-Limit, Continuity in Higher Dimension.pptx', '1.sql', '16763569014867651763610541383678.jpg', '2 (1).blend', '2- notes.pptx.pdf', '2.blend', '2.sql', '2022mpireportenpdf.pdf', '20230917_171023.jpg', '20240105_160411.jpg', '20240105_160435.jpg', '20240120_151319 (1).jpg', '20240120_151319-_1_.jpeg', '20240120_151319.jpg', '20240310_103554 (1).jpg', '20240310_103554.jpg', '20240424_234526.jpg', '221000003_Aditya_Chandrakar_ML_6.docx', '221000026_Lab7 (1).docx', '221000028_Lab4.pdf', '221000029_Akhil Shivaram chowdary kommineni.(DC -Assignment 7).pdf', '221000053 ML LAB - 05.pdf', '221000054_Lab1.pdf', '221000054_Networks_Assignment5.docx', '221000060 (1).pdf', '221000060 Varsha ML Lab 5.pdf', '221000060.pdf', '221000060_Exercise1.pdf', '221000060_Lab1.pdf', '221000060_VarshaSriNarla.pdf', '221020403_DSAI_AKSHAT_SHREE_MISHRA_DBMSLAB9.docx', '221020456_TOSHAN_KANWAR_ASSIGNMENT-8

In [211]:
pwd


'E:\\Users\\DELL\\Downloads'

In [213]:
os.chdir(os.pardir)

In [214]:
pwd

'E:\\Users\\DELL'

In [216]:
os.chdir('C:\\Users\\DELL')

In [217]:
pwd

'C:\\Users\\DELL'

In [218]:
os.listdir()

['.anaconda',
 '.android',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.dotnet',
 '.eclipse',
 '.emulator_console_auth_token',
 '.git',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.mozilla',
 '.p2',
 '.spyder-py3',
 '.templateengine',
 '.thumbnails',
 '.VirtualBox',
 '.virtualenvs',
 '.vivado_hls',
 '.vscode',
 '.Xilinx',
 '100-days-of-ml.ipynb',
 '41MUX',
 'Alexenet skeleton yt.ipynb',
 'Alexnet skeleton.ipynb',
 'anaconda3',
 'AppData',
 'Application Data',
 'aug_test.csv',
 'Banglore House Price Prediction.ipynb',
 'bangloreHouse.zip',
 'battery-report.html',
 'bintogray',
 'Bivariate Analysis .ipynb',
 'books',
 'books.csv',
 'Breast_cancer_Data.csv - Breast_cancer_Data.csv.csv',
 'C',
 'calc',
 'clatwobit',
 'Cleaning Industrial Dataset .ipynb',
 'Contacts',
 'Cookies',
 'counter',
 'data',
 'data.zip',
 'Desktop',
 'DFF',
 'DFF2',
 'displayhelloworld',
 'Documen

In [220]:
df=pd.read_csv('example.csv')

In [221]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [222]:
df=pd.read_csv('bank.csv')

In [223]:
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [225]:
df[:5]

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [226]:
df.describe()

age       balance          day     duration     campaign  \
count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000   
mean     41.170095   1422.657819    15.915284   263.961292     2.793630   
std      10.576211   3009.638142     8.247667   259.856633     3.109807   
min      19.000000  -3313.000000     1.000000     4.000000     1.000000   
25%      33.000000     69.000000     9.000000   104.000000     1.000000   
50%      39.000000    444.000000    16.000000   185.000000     2.000000   
75%      49.000000   1480.000000    21.000000   329.000000     3.000000   
max      87.000000  71188.000000    31.000000  3025.000000    50.000000   

             pdays     previous  
count  4521.000000  4521.000000  
mean     39.766645     0.542579  
std     100.121124     1.693562  
min      -1.000000     0.000000  
25%      -1.000000     0.000000  
50%      -1.000000     0.000000  
75%      -1.000000     0.000000  
max     871.000000    25.000000

In [227]:
df['age'].mean()

41.17009511170095

In [232]:
len(df['job'].unique())

12

In [233]:
df['job'].value_counts()

job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

In [238]:
len(df[df['marital']=='married'])

2797

In [241]:
import torch

In [242]:
torch.__version__

'2.2.1+cpu'

In [243]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [244]:
x=torch.from_numpy(arr)

In [245]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [247]:
x.dtype

torch.int32

In [248]:
x=torch.as_tensor(arr)

In [249]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [250]:
arr2d=np.arange(0,10).reshape(5,2)

In [252]:
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [254]:
arr2d=torch.from_numpy(arr2d)

In [255]:
arr2d

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]], dtype=torch.int32)

In [256]:
arr[0]=99

In [257]:
arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [258]:
x #creates a direct link between tensor and array

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [259]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [260]:
ten1=torch.from_numpy(arr)
ten1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [261]:
ten2=torch.tensor(arr)
ten2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [262]:
arr[0]=999
arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [263]:
ten1 #the tensor created using 'from numpy' is a direct link to the original array. so the changes made will be reflected 

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [264]:
ten2 #is a copy of the array used. so changes not reflected

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [268]:
torch.zeros(3,3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [270]:
torch.arange(0,11,2).reshape(3,2)

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])

In [271]:
torch.linspace(0,1,20)

tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])

In [272]:
torch.randn(5,5)

tensor([[ 1.3586, -0.5126,  0.0585,  1.9515,  1.2679],
        [ 0.8470, -0.9113,  0.7781, -1.1506, -0.7846],
        [-0.2239, -0.2956, -0.4874, -1.0736, -0.2174],
        [ 1.0470, -0.2734,  0.7336,  0.0059, -1.0658],
        [ 0.1044, -0.8692, -0.4309, -1.4056, -0.5677]])

In [273]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 7,  4,  9,  1,  2],
        [ 9,  0, 10,  6,  6],
        [10,  4,  7,  6,  6],
        [ 6, 10,  5,  1,  6],
        [ 4,  5, 10,  2,  6]])

In [280]:
arr=np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

In [282]:
x=torch.arange(0,6)
x

tensor([0, 1, 2, 3, 4, 5])

In [283]:
x.view(3,2) #changes not reflected in original array, but latest data is shown. 

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [284]:
x

tensor([0, 1, 2, 3, 4, 5])

In [287]:
x.reshape(3,2) #changes reflected, dunno why its not showing up here
x

tensor([0, 1, 2, 3, 4, 5])

In [290]:
x=torch.arange(50)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [293]:
x.view(-1,5)  #-1 realises what the missing dimension should be 

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]])

In [322]:
a=torch.tensor([1,3,5,7])
b=torch.tensor([2,4,6,8])

In [323]:
a

tensor([1, 3, 5, 7])

In [324]:
b

tensor([2, 4, 6, 8])

In [325]:
a+b

tensor([ 3,  7, 11, 15])

In [326]:
a.mul(b) #just shows the answer, doesn't store anywhere 

tensor([ 2, 12, 30, 56])

In [327]:
a.mul_(b) # reassigns the answer to a because of the underscore 

tensor([ 2, 12, 30, 56])

In [328]:
a.dtype

torch.int64

In [329]:
b.dtype

torch.int64

In [330]:
a.dot(b)

tensor(680)

In [331]:
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [332]:
b=torch.tensor([[10,11,12], [13,14,15],[16,17,18]])

In [333]:
a.shape

torch.Size([3, 3])

In [334]:
b.shape

torch.Size([3, 3])

In [335]:
a.dtype

torch.int64

In [336]:
b.dtype

torch.int64

In [337]:
torch.mm(a,b)

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

In [338]:
a.numel()

9

In [343]:
np.random.seed(42)
torch.manual_seed(42)

In [344]:
arr=np.random.randint(0,5,6)
arr

array([3, 4, 2, 4, 4, 1])

In [345]:
x=torch.tensor(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [346]:
x=x.type(torch.int64)

In [347]:
x.dtype

torch.int64

In [370]:
x=x.reshape(3,2)
x

tensor([[0, 0],
        [2, 4],
        [4, 1]])

In [371]:
x[:, 1].reshape(3,1)

tensor([[0],
        [4],
        [1]])

In [372]:
y=torch.clone(x)

In [377]:
y=y.mul(y)

In [378]:
y

tensor([[100, 100],
        [  4,  16],
        [ 16,   1]])

In [379]:
x.shape

torch.Size([3, 2])

In [385]:
y=torch.randint(0,5,(2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [386]:
x.mm(y)

tensor([[ 0,  0,  0],
        [20,  8,  2],
        [12,  9,  4]])

In [1]:
import os
print(os.getcwd())  # This prints the current working directory (where the notebook is saved)


C:\Users\DELL
