In [2]:
import torch
from torch import nn 
import torch.nn.functional as F

In [3]:
import numpy as np

In [4]:
with open(r'C:\Users\DELL\OneDrive\Desktop\PYTORCH_NOTEBOOKS\Data\shakespeare.txt', 'r', encoding='utf8') as f:
    text=f.read()

In [5]:
type(text)

str

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text)

5445609

In [8]:
all_characters=set(text)
len(all_characters)

84

In [9]:
#takes number value and returns the corresponding char 
decoder=dict(enumerate(all_characters))
    

In [10]:
decoder

{0: '-',
 1: 'D',
 2: 'b',
 3: ')',
 4: 'B',
 5: 'e',
 6: '3',
 7: '5',
 8: 'Z',
 9: '.',
 10: 'g',
 11: '7',
 12: 'Q',
 13: 'n',
 14: '?',
 15: 'k',
 16: ' ',
 17: 'I',
 18: 'T',
 19: 'i',
 20: 'x',
 21: 'N',
 22: '9',
 23: '|',
 24: 't',
 25: 'q',
 26: '[',
 27: 'U',
 28: '\n',
 29: 'J',
 30: '1',
 31: 'l',
 32: '8',
 33: 'r',
 34: '4',
 35: 'L',
 36: 'K',
 37: 'h',
 38: 'A',
 39: 'z',
 40: 'C',
 41: ']',
 42: '!',
 43: 'c',
 44: '`',
 45: '2',
 46: '&',
 47: 'P',
 48: '"',
 49: 'v',
 50: '_',
 51: 'Y',
 52: 'o',
 53: 'R',
 54: 'V',
 55: 'p',
 56: 'F',
 57: ':',
 58: 'G',
 59: '>',
 60: '0',
 61: 'H',
 62: 'f',
 63: 'W',
 64: 'S',
 65: 'm',
 66: 'O',
 67: 'a',
 68: '<',
 69: ',',
 70: "'",
 71: 'X',
 72: '}',
 73: ';',
 74: 'y',
 75: 'M',
 76: 'j',
 77: 'u',
 78: 'd',
 79: '(',
 80: 'E',
 81: 's',
 82: 'w',
 83: '6'}

In [11]:
#letter -> number
encoder={char: ind for ind, char in decoder.items()}

In [12]:
encoder

{'-': 0,
 'D': 1,
 'b': 2,
 ')': 3,
 'B': 4,
 'e': 5,
 '3': 6,
 '5': 7,
 'Z': 8,
 '.': 9,
 'g': 10,
 '7': 11,
 'Q': 12,
 'n': 13,
 '?': 14,
 'k': 15,
 ' ': 16,
 'I': 17,
 'T': 18,
 'i': 19,
 'x': 20,
 'N': 21,
 '9': 22,
 '|': 23,
 't': 24,
 'q': 25,
 '[': 26,
 'U': 27,
 '\n': 28,
 'J': 29,
 '1': 30,
 'l': 31,
 '8': 32,
 'r': 33,
 '4': 34,
 'L': 35,
 'K': 36,
 'h': 37,
 'A': 38,
 'z': 39,
 'C': 40,
 ']': 41,
 '!': 42,
 'c': 43,
 '`': 44,
 '2': 45,
 '&': 46,
 'P': 47,
 '"': 48,
 'v': 49,
 '_': 50,
 'Y': 51,
 'o': 52,
 'R': 53,
 'V': 54,
 'p': 55,
 'F': 56,
 ':': 57,
 'G': 58,
 '>': 59,
 '0': 60,
 'H': 61,
 'f': 62,
 'W': 63,
 'S': 64,
 'm': 65,
 'O': 66,
 'a': 67,
 '<': 68,
 ',': 69,
 "'": 70,
 'X': 71,
 '}': 72,
 ';': 73,
 'y': 74,
 'M': 75,
 'j': 76,
 'u': 77,
 'd': 78,
 '(': 79,
 'E': 80,
 's': 81,
 'w': 82,
 '6': 83}

In [13]:
encoded_text=np.array([encoder[char] for char in text])

In [14]:
encoded_text[:500]

array([28, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 30, 28, 16, 16, 56, 33, 52, 65, 16, 62, 67, 19,
       33,  5, 81, 24, 16, 43, 33,  5, 67, 24, 77, 33,  5, 81, 16, 82,  5,
       16, 78,  5, 81, 19, 33,  5, 16, 19, 13, 43, 33,  5, 67, 81,  5, 69,
       28, 16, 16, 18, 37, 67, 24, 16, 24, 37,  5, 33,  5,  2, 74, 16,  2,
        5, 67, 77, 24, 74, 70, 81, 16, 33, 52, 81,  5, 16, 65, 19, 10, 37,
       24, 16, 13,  5, 49,  5, 33, 16, 78, 19,  5, 69, 28, 16, 16,  4, 77,
       24, 16, 67, 81, 16, 24, 37,  5, 16, 33, 19, 55,  5, 33, 16, 81, 37,
       52, 77, 31, 78, 16,  2, 74, 16, 24, 19, 65,  5, 16, 78,  5, 43,  5,
       67, 81,  5, 69, 28, 16, 16, 61, 19, 81, 16, 24,  5, 13, 78,  5, 33,
       16, 37,  5, 19, 33, 16, 65, 19, 10, 37, 24, 16,  2,  5, 67, 33, 16,
       37, 19, 81, 16, 65,  5, 65, 52, 33, 74, 57, 28, 16, 16,  4, 77, 24,
       16, 24, 37, 52, 77, 16, 43, 52, 13, 24, 33, 67, 43, 24,  5, 78, 16,
       24, 52, 16, 24, 37

In [15]:
decoder[68]

'<'

In [16]:
import numpy as np

def one_hot_encoder(encoded_text, num_uni_chars):
    # encoded_text ---> batch of encoded text 
    # num_uni_chars ---> number of unique characters
    
    # Initialize the one-hot encoding array with zeros
    one_hot = np.zeros((encoded_text.size, num_uni_chars), dtype=np.float32)
    
    # Set specific indices to 1.0 for one-hot encoding
    one_hot[np.arange(encoded_text.size), encoded_text.flatten()] = 1.0
    
    # Reshape to match the original batch dimensions with one-hot encoding depth
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))
    
    return one_hot


In [17]:
arr=np.array([1,2,0])

In [18]:
arr

array([1, 2, 0])

In [19]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [20]:
example_text=np.arange(10)

In [21]:
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
example_text.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    #x is the encoded text of seq_len 
    #y is the encoded shifted by 1 
    
    chars_per_batch=samp_per_batch*seq_len
    num_batches_avail=int(len(encoded_text)/chars_per_batch)
    encoded_text=encoded_text[:num_batches_avail*chars_per_batch]
    
    encoded_text=encoded_text.reshape((samp_per_batch,-1))
    
    for n in range(0, encoded_text.shape[1], seq_len):
        x=encoded_text[:,n:n+seq_len]
        
        y=np.zeros_like(x)
        
        try:
            y[:, :-1]=x[:,1:]
            
            y[:,-1]=encoded_text[:,n+seq_len]
            
            
        except:
            y[:,:-1]=x[:,1:]
            y[:,-1]=encoded_text[:,0]
            
        yield x,y
    

In [40]:
sample_text=np.arange(20)


In [41]:
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
batch_generator=generate_batches(sample_text, samp_per_batch=2, seq_len=5)

In [43]:
x,y=next(batch_generator)

In [44]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [45]:
y #the numbers below are one shifted to the right of x 

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [94]:
class CharModel(nn.Module):
    
    def __init__(self, all_chars, num_hidden=256, num_layers=5, drop_prob=0.5, use_gpu=False):
        super().__init__()
        
        self.drop_prob=drop_prob
        self.num_layers=num_layers
        self.num_hidden=num_hidden
        self.use_gpu=use_gpu
        
        self.all_chars=all_chars
        self.decoder=dict(enumerate(all_chars))
        self.encoder={char: ind for ind, char in self.decoder.items()}
        
        self.lstm=nn.LSTM(len(self.all_chars), num_hidden, num_layers, dropout=drop_prob, batch_first=True)
        
        self.dropout=nn.Dropout(drop_prob)
        
        self.fc_linear=nn.Linear(num_hidden, len(self.all_chars))
        
    def forward(self, x, hidden):
        lstm_output, hidden=self.lstm(x, hidden)
        
        drop_output=self.dropout(lstm_output)
        
        drop_output=drop_output.contiguous().view(-1, self.num_hidden)
        
        final_out=self.fc_linear(drop_output)
        
        return final_out, hidden
    
    def hidden_state(self, batch_size):
        if self.use_gpu:
            hidden=(torch.zeros(self.num_layers,batch_size, self.num_hidden).cuda(),
                    torch.zeros(self.num_layers,batch_size, self.num_hidden).cuda())
        else:
            hidden=(torch.zeros(self.num_layers,batch_size, self.num_hidden),
                    torch.zeros(self.num_layers,batch_size, self.num_hidden))
            
        return hidden
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

In [95]:
model=CharModel(all_chars=all_characters,
               num_hidden=512,
               num_layers=3,
               drop_prob=0.5,
               use_gpu=False)

In [96]:
total_param=[]

for p in model.parameters():
    total_param.append(int(p.numel()))

In [97]:
total_param

[172032,
 1048576,
 2048,
 2048,
 1048576,
 1048576,
 2048,
 2048,
 1048576,
 1048576,
 2048,
 2048,
 43008,
 84]

In [98]:
sum(total_param) #size of the dataset approx which is a good thing, else model overfits/underfits 

5470292

In [99]:
optimizer=torch.optim.Adam(model.parameters(), lr=0.001)
criterion=nn.CrossEntropyLoss()

In [100]:
train_percent=0.1

In [101]:
train_ind=int(len(encoded_text)*train_percent)

In [102]:
train_data=encoded_text[:train_ind]
val_data=encoded_text[train_ind:]

In [103]:
len(train_data)

544560

In [104]:
len(val_data)

4901049

In [109]:
epochs=1
batch_size=100
seq_len=100
tracker=0
num_chars=max(encoded_text)+1

In [111]:
model.train()
use_gpu = torch.cuda.is_available()
if use_gpu:
    model=model.cuda()
    
for i in range(epochs):
    hidden=model.hidden_state(batch_size)
    for x,y in generate_batches(train_data, batch_size, seq_len):
        tracker+=1
        x=one_hot_encoder(x, num_chars)
        inputs=torch.from_numpy(x)
        targets=torch.from_numpy(y)
        
        if model.use_gpu:
            inputs=inputs.cuda()
            targets=targets.cuda()
            
        hidden=tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output, hidden=model.forward(inputs, hidden)
        loss=criterion(lstm_output, targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        nn.utils.clip_grad_norm(model.parameters(), max_norm=5)
        
        optimizer.step()
        
        if tracker%25==0:
            val_hidden=model.hidden_state(batch_size)
            val_losses=[]
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                x=one_hot_encoder(x, num_chars)
                inputs=torch.from_numpy(x)
                targets=torch.from_numpy(y)
                
                if model.use_gpu:
                    inputs=inputs.cuda()
                    targets=targets.cuda()
                    
                val_hidden=tuple([state.data for state in val_hidden])
                
                lstm_output,val_hidden=model.forward(inputs, val_hidden)
                val_loss=criterion(lstm_output, targets.view(batch_size*seq_len).long())
                
                val_losses.append(val_loss.item())
                
            model.train()
            print(f"EPOCH: {i} Step: {tracker} VAL LOSS: {val_loss.item()}")
            

C:\Users\DELL\AppData\Local\Temp\ipykernel_3056\2953598870.py:27: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), max_norm=5)


EPOCH: 0 Step: 75 VAL LOSS: 3.195875883102417
EPOCH: 0 Step: 100 VAL LOSS: 3.1826040744781494


In [112]:
model_name='hidden512_layers3_shakes.net'

In [113]:
torch.save(model.state_dict(), model_name)

In [120]:
import numpy as np
import torch
import torch.nn.functional as F

# Define one_hot_encoded function
def one_hot_encoded(encoded_text, num_chars):
    one_hot = np.zeros((encoded_text.size, num_chars))
    one_hot[np.arange(encoded_text.size), encoded_text] = 1
    return one_hot

# Define predict_next_char function
def predict_next_char(model, char, hidden=None, k=1):
    # Encoding the character
    encoded_text = model.encoder[char]
    encoded_text = np.array([[encoded_text]])
    
    # One-hot encoding the encoded character
    encoded_text = one_hot_encoded(encoded_text, len(model.all_chars))
    inputs = torch.from_numpy(encoded_text).float().unsqueeze(0)  # Add batch dimension
    
    # Passing the hidden state without gradients
    hidden = tuple([state.data for state in hidden])
    
    # Getting LSTM output and new hidden state
    lstm_out, hidden = model(inputs, hidden)
    
    # Calculating probabilities
    probs = F.softmax(lstm_out, dim=1).data
    probs, index_positions = probs.topk(k)
    
    # Converting to numpy for manipulation
    index_positions = index_positions.numpy().squeeze()
    probs = probs.numpy().flatten()
    probs = probs / probs.sum()  # Normalize to get probabilities
    
    # Selecting a character based on probabilities
    char = np.random.choice(index_positions, p=probs)
    
    # Return the predicted character and the hidden state
    return model.decoder[char], hidden


In [121]:
def generate_text(model, size, seed='The', k=1):
    model.cpu()
    model.eval()
    output_chars=[c for c in seed]
    
    hidden=model.hidden_state(1)
    
    for char in seed:
        char, hidden=predict_next_char(model, char, hidden, k=k)
        
    output_chars.append(char)
    
    for i in range(size):
        char,hidden=predict_next_char(model, output_chars[-1], hidden, k=k)
        
        output_chars.append(char)
        
    return ''.join(output_chars)

In [122]:
print(generate_text(model, 1000, seed='The ', k=3))

The e   e te   t  e e e  e e te  t  e   te  e   e      e e  t   e     t  e  ee    t  e   e         tee  te          e   e eete  e t e  t  t tett ee    t        e  ee      t  tee  e  ee  te  ee    e   et   e     ee ee      t eet tt ee     eteet   te  t    eet  ettte   tee      t e     ee tee e   e   t  ete  e   t   t ee         eeeete     e  tt    e e          e      ee   e t   e      tt e    eee   e    te     e  e e e e  e   ee   e    ee    e  t  e ee   t       t   e teee     eet  e          e et    tte  e     t  te ete      t          e et eee ee     t e          ee  t t     tt      ee    eet      et tte     t     t   ett  e    t  t       t t   ee    e     t t   e t   ee  t t    e  t t tt  e   t      t   t  te   e   et t    e e     e  e t ee teetee  t   t  te  t   e     t e eeeee        e  e e t te     e   e  e  e e     e t et e   ete  tee  t   t       e e ette  tet  ee tet eet  t ettt      e   tee e ete  ett teee ete     tt eet        ttt      e  tt   t et     e e ee e      e   ee e 